spring:
  application:
    name: u0date
  data:
    mongodb:
      uri: mongodb://localhost:27017/
      database: u0date
  security:
    jwt:
      secret_key: ${SECRET_KEY:wfhs5poWwHroWSLYl8/eUVIhVUlw/uay4+u1YPJtyT0=}